name: advanced_flutter_platform
repository: https://github.com/yourusername/advanced_flutter_platform

packages:
  - packages/**

command:
  version:
    linkToCommits: false
    workspaceChangelog: false

  bootstrap:
    runPubGetInParallel: true
    runPubGetOffline: false

scripts:
  analyze:
    run: melos exec -- flutter analyze
    description: Run Flutter analyzer for all packages

  format:
    run: melos exec -- dart format .
    description: Format all packages

  test:
    run: melos exec -- flutter test --no-pub --coverage
    description: Run all Flutter tests

  test:unit:
    run: melos exec -- flutter test test/unit
    description: Run unit tests only

  clean:
    run: melos exec -- flutter clean
    description: Clean all packages

  get:
    run: melos exec -- flutter pub get
    description: Get dependencies for all packages

  build:runner:
    run: melos exec -- flutter pub run build_runner build --delete-conflicting-outputs
    description: Run build_runner for code generation
